version: "3.8"

services:
  # Apache + PHP service
  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - mysql
    # For development, you might want selective mounting to preserve installed extensions
    # volumes:
    #   - ./src:/var/www/html/src
    #   - ./public:/var/www/html/public
    #   - ./index.php:/var/www/html/index.php

  # MySQL Database service
  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=scandiweb
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-network
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # For DB initialization scripts
      - mysql-data:/var/lib/mysql # Persistent data storage

  # phpMyAdmin for managing MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - app-network
    depends_on:
      - mysql

# Network configuration for service communication
networks:
  app-network:
    driver: bridge

# Persistent volumes
volumes:
  mysql-data:
