version: "3.8"

services:
  # Apache + PHP service
  www:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APACHE_SERVER_NAME=localhost
    volumes:
      - ./src:/var/www/html/src # Mount only your source code directory
      - ./public:/var/www/html/public # Mount public files
      # Don't mount system directories like vendor, extensions, etc.
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - mysql

  # MySQL Database service
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=scandiweb
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-network
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # Generates the files for seeding db

  # phpMyAdmin for managing MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - app-network

# Network configuration for service communication
networks:
  app-network:
    driver: bridge
