version: "3.8"

services:
  www:
    image: php:apache
    build: .

    volumes:
      - "./:/var/www/html" # Syncs current project directory with Apache root directory in container
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=scandiweb
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=password
    networks:
      - app-network
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # generates the files for seeding db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - app-network

networks:
  app-network:
