version: "3.8"

services:
  # Apache + PHP
  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scandiweb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
