name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy SQL file to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa db/scandiweb.sql ubuntu@3.83.213.206:/home/ubuntu/scandiweb.sql

      - name: Deploy to EC2 and import SQL
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.83.213.206 << EOF
            cd /home/ubuntu/scandiweb-Junior-Full-Stack-Developer-test-task
            git pull origin main

            echo "${{ secrets.ENV_FILE }}" > .env

            # Drop and recreate DB
            mysql -u "${{ secrets.DB_USER }}" -p"${{ secrets.DB_PASSWORD }}" -e "DROP DATABASE IF EXISTS \\\`${{ secrets.DB_NAME }}\\\`; CREATE DATABASE \\\`${{ secrets.DB_NAME }}\\\`;"

            # Import SQL file
            mysql -u "${{ secrets.DB_USER }}" -p"${{ secrets.DB_PASSWORD }}" "${{ secrets.DB_NAME }}" < /home/ubuntu/scandiweb.sql
          EOF
