name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2 and setup DB
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.83.213.206 << 'EOF'
            cd /home/ubuntu/scandiweb-Junior-Full-Stack-Developer-test-task

            git pull origin main

            echo "${{ secrets.ENV_FILE }}" > .env

            mysql -u root -p'root' -e "DROP DATABASE IF EXISTS scandiweb; CREATE DATABASE scandiweb;"

            mysql -u root -p'root' scandiweb < /home/ubuntu/scandiweb.sql
          EOF
